### ISSUE TITLE
 Unable to locate credentials

### ISSUE THREAD

**Issue by OGsiji** [Wittline/uber-expenses-tracking#7]
![Screenshot from 2021-12-08 10-47-13](https://user-images.githubusercontent.com/67172880/145187548-1aaf818f-625e-48fb-9c9e-27fccde9e9e3.png)
![Screenshot from 2021-12-08 10-47-13](https://user-images.githubusercontent.com/67172880/145187672-719b10d3-1522-43d9-9a90-31dc72722a6e.png)

I keep having issues around this, Also where can I get the receipts

**Comment by Wittline** [comment]
> ![Screenshot from 2021-12-08 10-47-13](https://user-images.githubusercontent.com/67172880/145187548-1aaf818f-625e-48fb-9c9e-27fccde9e9e3.png) ![Screenshot from 2021-12-08 10-47-13](https://user-images.githubusercontent.com/67172880/145187672-719b10d3-1522-43d9-9a90-31dc72722a6e.png)
> 
> I keep having issues around this, Also where can I get the receipts

Hi @OGsiji You should set your credentials on your local machine, I did this using my own receipts, if you want my receipts please let me know..
